# Generated by Django 5.2.16 on 2026-07-20 15:15

from django.db import migrations

def create_general_circle(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Circle = apps.get_model('posts', 'Circle')
    Post = apps.get_model('posts', 'Post')

    # Get the first user to be the creator of General circle
    first_user = User.objects.order_by('id').first()
    if not first_user:
        # If no users exist, we can't create one. But in production/development there is usually at least one.
        # Let's fallback to not doing anything if there are no users.
        return

    # Create the general circle
    general_circle, created = Circle.objects.get_or_create(
        name="General",
        defaults={
            "description": "The default public circle for everyone.",
            "created_by": first_user
        }
    )

    # Add all existing users as members
    all_users = User.objects.all()
    general_circle.members.add(*all_users)

    # Add all existing posts to the general circle
    all_posts = Post.objects.all()
    for post in all_posts:
        post.circles.add(general_circle)

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_circle_post_circles'),
    ]

    operations = [
        migrations.RunPython(create_general_circle),
    ]
