# Generated by Django 5.2.16 on 2026-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_bubble_theme',
            field=models.CharField(default='indigo', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_wallpaper',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
